# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{lsl}
  s.version = "0.1.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["mharris717"]
  s.date = %q{2010-12-31}
  s.default_executable = %q{lsl}
  s.description = %q{little shell language}
  s.email = %q{mharris717@gmail.com}
  s.executables = ["lsl"]
  s.extra_rdoc_files = [
    "LICENSE.txt",
    "README.rdoc"
  ]
  s.files = [
    ".document",
    ".rspec",
    "Gemfile",
    "Gemfile.lock",
    "LICENSE.txt",
    "README.rdoc",
    "Rakefile",
    "VERSION",
    "bin/lsl",
    "lib/lsl.rb",
    "lib/lsl/command/compound.rb",
    "lib/lsl/command/execution.rb",
    "lib/lsl/command/single.rb",
    "lib/lsl/ext/ext.rb",
    "lib/lsl/grammars/base.treetop",
    "lib/lsl/grammars/compound_command.treetop",
    "lib/lsl/grammars/file.treetop",
    "lib/lsl/grammars/list.treetop",
    "lib/lsl/grammars/quoting.treetop",
    "lib/lsl/grammars/single_command.treetop",
    "lib/lsl/mapping/mapping.rb",
    "lib/lsl/sandbox.rb",
    "lib/lsl/server.rb",
    "lib/lsl/shell.rb",
    "lsl.gemspec",
    "spec/compound_command_spec.rb",
    "spec/lsl_spec.rb",
    "spec/mock_dir/a.txt",
    "spec/mock_dir/b.txt",
    "spec/mock_dir/log.txt",
    "spec/mock_dir/output.txt",
    "spec/quoting_spec.rb",
    "spec/shell_spec.rb",
    "spec/single_command_spec.rb",
    "spec/spec_helper.rb",
    "to"
  ]
  s.homepage = %q{http://github.com/mharris717/lsl}
  s.licenses = ["MIT"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.6}
  s.summary = %q{little shell language}
  s.test_files = [
    "spec/compound_command_spec.rb",
    "spec/lsl_spec.rb",
    "spec/quoting_spec.rb",
    "spec/shell_spec.rb",
    "spec/single_command_spec.rb",
    "spec/spec_helper.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::RubyGemsVersion) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<andand>, [">= 0"])
      s.add_runtime_dependency(%q<treetop>, [">= 0"])
      s.add_runtime_dependency(%q<mharris_ext>, [">= 0"])
      s.add_development_dependency(%q<rspec>, ["~> 2.1.0"])
      s.add_development_dependency(%q<bundler>, ["~> 1.0.0"])
      s.add_development_dependency(%q<jeweler>, ["~> 1.5.1"])
      s.add_development_dependency(%q<rcov>, [">= 0"])
    else
      s.add_dependency(%q<andand>, [">= 0"])
      s.add_dependency(%q<treetop>, [">= 0"])
      s.add_dependency(%q<mharris_ext>, [">= 0"])
      s.add_dependency(%q<rspec>, ["~> 2.1.0"])
      s.add_dependency(%q<bundler>, ["~> 1.0.0"])
      s.add_dependency(%q<jeweler>, ["~> 1.5.1"])
      s.add_dependency(%q<rcov>, [">= 0"])
    end
  else
    s.add_dependency(%q<andand>, [">= 0"])
    s.add_dependency(%q<treetop>, [">= 0"])
    s.add_dependency(%q<mharris_ext>, [">= 0"])
    s.add_dependency(%q<rspec>, ["~> 2.1.0"])
    s.add_dependency(%q<bundler>, ["~> 1.0.0"])
    s.add_dependency(%q<jeweler>, ["~> 1.5.1"])
    s.add_dependency(%q<rcov>, [">= 0"])
  end
end

